spring:
  profiles:
    active: dev
  # config for solving swagger documentationPluginsBootstrapper err
  # can be remove if disable swagger
  # ref: https://webfuse.in/blogs/issues-troubleshooting/how-to-fix-failed-to-start-bean-documentationpluginsbootstrapper-use-springdoc-openapi-ui/
  mvc:
    pathmatch.matching-strategy: ANT_PATH_MATCHER
swagger:
  enabled: true
