// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommender/recommender.proto

package com.bruce.grpc.proto.recommender;

import com.bruce.grpc.proto.moviecontroller.Moviecontroller;
import com.bruce.grpc.proto.common.Common;

public final class Recommender {
  private Recommender() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_RecommenderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_RecommenderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recommender_RecommenderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recommender_RecommenderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035recommender/recommender.proto\022\013recomme" +
      "nder\032\023common/common.proto\032%moviecontroll" +
      "er/moviecontroller.proto\"B\n\022RecommenderR" +
      "equest\022\016\n\006userid\030\001 \001(\t\022\034\n\005movie\030\002 \001(\0132\r." +
      "common.Movie\"3\n\023RecommenderResponse\022\034\n\005m" +
      "ovie\030\001 \001(\0132\r.common.Movie2r\n\022Recommender" +
      "Service\022\\\n\023getRecommendedMovie\022\037.recomme" +
      "nder.RecommenderRequest\032 .recommender.Re" +
      "commenderResponse\"\000(\001B$\n com.bruce.grpc." +
      "proto.recommenderP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.getDescriptor(),
          Moviecontroller.getDescriptor(),
        });
    internal_static_recommender_RecommenderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recommender_RecommenderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_RecommenderRequest_descriptor,
        new java.lang.String[] { "Userid", "Movie", });
    internal_static_recommender_RecommenderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recommender_RecommenderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recommender_RecommenderResponse_descriptor,
        new java.lang.String[] { "Movie", });
    Common.getDescriptor();
    Moviecontroller.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
