// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moviestore/moviestore.proto

package com.bruce.grpc.proto.moviestore;

import com.bruce.grpc.proto.moviecontroller.Moviecontroller;
import com.bruce.grpc.proto.common.Common;

public final class Moviestore {
  private Moviestore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moviestore_MovieStoreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moviestore_MovieStoreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moviestore_MovieStoreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_moviestore_MovieStoreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033moviestore/moviestore.proto\022\nmoviestor" +
      "e\032\023common/common.proto\032%moviecontroller/" +
      "moviecontroller.proto\"1\n\021MovieStoreReque" +
      "st\022\034\n\005genre\030\001 \001(\0162\r.common.Genre\"2\n\022Movi" +
      "eStoreResponse\022\034\n\005movie\030\001 \001(\0132\r.common.M" +
      "ovie2c\n\021MovieStoreService\022N\n\tgetMovies\022\035" +
      ".moviestore.MovieStoreRequest\032\036.moviesto" +
      "re.MovieStoreResponse\"\0000\001B#\n\037com.bruce.g" +
      "rpc.proto.moviestoreP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.getDescriptor(),
          Moviecontroller.getDescriptor(),
        });
    internal_static_moviestore_MovieStoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_moviestore_MovieStoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moviestore_MovieStoreRequest_descriptor,
        new java.lang.String[] { "Genre", });
    internal_static_moviestore_MovieStoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_moviestore_MovieStoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_moviestore_MovieStoreResponse_descriptor,
        new java.lang.String[] { "Movie", });
    Common.getDescriptor();
    Moviecontroller.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
