// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moviestore/moviestore.proto

package com.bruce.grpc.proto.moviestore;

import com.bruce.grpc.proto.common.MovieOrBuilder;
import com.bruce.grpc.proto.common.Movie;

public interface MovieStoreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moviestore.MovieStoreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.Movie movie = 1;</code>
   * @return Whether the movie field is set.
   */
  boolean hasMovie();
  /**
   * <code>.common.Movie movie = 1;</code>
   * @return The movie.
   */
  Movie getMovie();
  /**
   * <code>.common.Movie movie = 1;</code>
   */
  MovieOrBuilder getMovieOrBuilder();
}
