// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userpreferences/userpreferences.proto

package com.bruce.grpc.proto.userpreferences;

import com.bruce.grpc.proto.moviecontroller.Moviecontroller;
import com.bruce.grpc.proto.common.Common;

public final class Userpreferences {
  private Userpreferences() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userpreferences_UserPreferencesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userpreferences_UserPreferencesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userpreferences_UserPreferencesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userpreferences_UserPreferencesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%userpreferences/userpreferences.proto\022" +
      "\017userpreferences\032\023common/common.proto\032%m" +
      "oviecontroller/moviecontroller.proto\"F\n\026" +
      "UserPreferencesRequest\022\016\n\006userid\030\001 \001(\t\022\034" +
      "\n\005movie\030\002 \001(\0132\r.common.Movie\"7\n\027UserPref" +
      "erencesResponse\022\034\n\005movie\030\001 \001(\0132\r.common." +
      "Movie2\211\001\n\026UserPreferencesService\022o\n\024getS" +
      "hortlistedMovies\022\'.userpreferences.UserP" +
      "referencesRequest\032(.userpreferences.User" +
      "PreferencesResponse\"\000(\0010\001B(\n$com.bruce.g" +
      "rpc.proto.userpreferencesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Common.getDescriptor(),
          Moviecontroller.getDescriptor(),
        });
    internal_static_userpreferences_UserPreferencesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userpreferences_UserPreferencesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userpreferences_UserPreferencesRequest_descriptor,
        new java.lang.String[] { "Userid", "Movie", });
    internal_static_userpreferences_UserPreferencesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_userpreferences_UserPreferencesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userpreferences_UserPreferencesResponse_descriptor,
        new java.lang.String[] { "Movie", });
    Common.getDescriptor();
    Moviecontroller.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
