// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userpreferences/userpreferences.proto

package com.bruce.grpc.proto.userpreferences;

import com.bruce.grpc.proto.common.Movie;
import com.bruce.grpc.proto.common.MovieOrBuilder;

public interface UserPreferencesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userpreferences.UserPreferencesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userid = 1;</code>
   * @return The userid.
   */
  java.lang.String getUserid();
  /**
   * <code>string userid = 1;</code>
   * @return The bytes for userid.
   */
  com.google.protobuf.ByteString
      getUseridBytes();

  /**
   * <code>.common.Movie movie = 2;</code>
   * @return Whether the movie field is set.
   */
  boolean hasMovie();
  /**
   * <code>.common.Movie movie = 2;</code>
   * @return The movie.
   */
  Movie getMovie();
  /**
   * <code>.common.Movie movie = 2;</code>
   */
  MovieOrBuilder getMovieOrBuilder();
}
